---

- name: update apt cache
  apt: update_cache=yes

- name: upgrade all safe packages
  apt: upgrade=safe

- name: install baseline packages
  apt: pkg={{ item }} state=installed
  with_items:
    - sudo
    - build-essential
    - vim
    - htop
    - iftop
    - iotop
    - git
  tags:
    - common

- name: remove puppet package
  apt: pkg=puppet state=removed
  tags:
    - common

- include: docker.yml
  tags:
    - common
    - docker
